CREATE SCHEMA IF NOT EXISTS jwt;

CREATE TABLE IF NOT EXISTS jwt.generated_token_audit (
    jwt_id VARCHAR(36) PRIMARY KEY,
    correlation_id VARCHAR(255),
    issued_at BIGINT NOT NULL,
    issued_at_tz TIMESTAMPTZ NOT NULL,
    client_id VARCHAR(36) NOT NULL,
    organization_id VARCHAR(36) NOT NULL,
    agreement_id VARCHAR(36) NOT NULL,
    eservice_id VARCHAR(36) NOT NULL,
    descriptor_id VARCHAR(36) NOT NULL,
    purpose_id VARCHAR(36) NOT NULL,
    purpose_version_id VARCHAR(36) NOT NULL,
    algorithm VARCHAR(50) NOT NULL,
    key_id VARCHAR(255) NOT NULL,
    typ VARCHAR(50),
    audience VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    not_before BIGINT NOT NULL,
    not_before_tz TIMESTAMPTZ NOT NULL,
    expiration_time BIGINT NOT NULL,
    expiration_time_tz TIMESTAMPTZ NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    cnf_jkt VARCHAR(255),
    digest_alg VARCHAR(50),
    digest_val VARCHAR(255),
    client_assertion_jwt_id VARCHAR(255) NOT NULL,
    dpop_jwt_id VARCHAR(255),
    origin_file_reference VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS jwt.client_assertion_audit (
    jwt_id VARCHAR(255),
    issued_at BIGINT NOT NULL,
    issued_at_tz TIMESTAMPTZ NOT NULL,
    algorithm VARCHAR(50) NOT NULL,
    key_id VARCHAR(255) NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(36) NOT NULL,
    audience VARCHAR(255) NOT NULL,
    expiration_time BIGINT NOT NULL,
    expiration_time_tz TIMESTAMPTZ NOT NULL,
    digest_alg VARCHAR(50),
    digest_val VARCHAR(255),
    generated_token_jwt_id VARCHAR(36) PRIMARY KEY,
    issued_at_raw DOUBLE PRECISION NOT NULL,
    expiration_time_raw DOUBLE PRECISION NOT NULL,
    origin_file_reference VARCHAR(255) NOT NULL,
    generated_token_issued_at BIGINT NOT NULL,
    generated_token_issued_at_tz TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_generated_token FOREIGN KEY (generated_token_jwt_id) REFERENCES jwt.generated_token_audit(jwt_id)
);

CREATE TABLE IF NOT EXISTS jwt.dpop_audit (
    typ VARCHAR(50) NOT NULL,
    alg VARCHAR(50) NOT NULL,
    jwk_kty VARCHAR(10) NOT NULL,
    jwk_n VARCHAR(2048),
    jwk_e VARCHAR(64),
    jwk_crv VARCHAR(10),
    jwk_x VARCHAR(512),
    jwk_y VARCHAR(512),
    htm VARCHAR(16) NOT NULL,
    htu VARCHAR(1024) NOT NULL,
    iat DOUBLE PRECISION NOT NULL,
    jti VARCHAR(255) NOT NULL,
    generated_token_jwt_id VARCHAR(36) PRIMARY KEY,
    origin_file_reference VARCHAR(255) NULL,
    generated_token_issued_at BIGINT NOT NULL,
    generated_token_issued_at_tz TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_generated_token FOREIGN KEY (generated_token_jwt_id) REFERENCES jwt.generated_token_audit(jwt_id)
);

CREATE SCHEMA IF NOT EXISTS infra;

CREATE TABLE IF NOT EXISTS infra.alb_logs_audit (
    trace_id VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    time VARCHAR(255) NOT NULL,
    elb VARCHAR(255) NOT NULL,
    client VARCHAR(50) NOT NULL,
    target VARCHAR(255),
    request_processing_time VARCHAR(255) NOT NULL,
    target_processing_time VARCHAR(255) NOT NULL,
    response_processing_time VARCHAR(255) NOT NULL,
    elb_status_code VARCHAR(255) NOT NULL,
    target_status_code VARCHAR(255),
    received_bytes BIGINT NOT NULL,
    sent_bytes BIGINT NOT NULL,
    request VARCHAR(1024) NOT NULL,
    user_agent VARCHAR(512),
    ssl_cipher VARCHAR(255),
    ssl_protocol VARCHAR(255),
    target_group_arn VARCHAR(512),
    domain_name VARCHAR(255),
    chosen_cert_arn VARCHAR(512),
    matched_rule_priority VARCHAR(255),
    request_creation_time VARCHAR(255),
    actions_executed VARCHAR(512),
    redirect_url VARCHAR(1024),
    error_reason VARCHAR(255),
    target_port_list VARCHAR(1024),
    target_status_code_list VARCHAR(1024),
    classification VARCHAR(255),
    classification_reason VARCHAR(255),
    conn_trace_id VARCHAR(255)
);

CREATE SCHEMA IF NOT EXISTS application;

CREATE TABLE IF NOT EXISTS application.begin_request_audit (
    correlation_id VARCHAR(255) NOT NULL,
    span_id VARCHAR(36) NOT NULL PRIMARY KEY,
    service VARCHAR(255) NOT NULL,
    service_version VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    http_method VARCHAR(255) NOT NULL,
    phase VARCHAR(255) NOT NULL,
    requester_ip_address VARCHAR(255),
    node_ip VARCHAR(255) NOT NULL,
    pod_name VARCHAR(255) NOT NULL,
    uptime_seconds BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    timestamp_tz TIMESTAMPTZ NOT NULL,
    amazon_trace_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS application.end_request_audit (
    correlation_id VARCHAR(255) NOT NULL,
    span_id VARCHAR(36) NOT NULL PRIMARY KEY,
    service VARCHAR(255) NOT NULL,
    service_version VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    http_method VARCHAR(255) NOT NULL,
    phase VARCHAR(255) NOT NULL,
    requester_ip_address VARCHAR(255),
    node_ip VARCHAR(255) NOT NULL,
    pod_name VARCHAR(255) NOT NULL,
    uptime_seconds BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    timestamp_tz TIMESTAMPTZ NOT NULL,
    amazon_trace_id VARCHAR(255),
    organization_id VARCHAR(36),
    http_response_status INTEGER NOT NULL,
    execution_time_ms BIGINT NOT NULL,
    user_id VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS application.end_request_session_token_exchange_audit (
    correlation_id VARCHAR(255) NOT NULL,
    span_id VARCHAR(36) NOT NULL PRIMARY KEY,
    service VARCHAR(255) NOT NULL,
    service_version VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    http_method VARCHAR(255) NOT NULL,
    phase VARCHAR(255) NOT NULL,
    requester_ip_address VARCHAR(255),
    node_ip VARCHAR(255) NOT NULL,
    pod_name VARCHAR(255) NOT NULL,
    uptime_seconds BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    timestamp_tz TIMESTAMPTZ NOT NULL,
    amazon_trace_id VARCHAR(255),
    organization_id VARCHAR(36),
    http_response_status INTEGER NOT NULL,
    execution_time_ms BIGINT NOT NULL,
    self_care_id VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS application.end_request_auth_server_audit (
    correlation_id VARCHAR(255) NOT NULL,
    span_id VARCHAR(36) NOT NULL PRIMARY KEY,
    service VARCHAR(255) NOT NULL,
    service_version VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    http_method VARCHAR(255) NOT NULL,
    phase VARCHAR(255) NOT NULL,
    requester_ip_address VARCHAR(255),
    node_ip VARCHAR(255) NOT NULL,
    pod_name VARCHAR(255) NOT NULL,
    uptime_seconds BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    timestamp_tz TIMESTAMPTZ NOT NULL,
    amazon_trace_id VARCHAR(255),
    organization_id VARCHAR(36),
    http_response_status INTEGER NOT NULL,
    execution_time_ms BIGINT NOT NULL,
    client_id VARCHAR(36),
    client_kind VARCHAR(255)
);