version: "3"
name: pagopa-interop-kpi
services:
  
  # MinIO is a local S3-compatible storage, to replace AWS S3 in local development
  minio:
    image: minio/minio:RELEASE.2024-02-06T21-36-22Z
    entrypoint: >
      /usr/bin/minio server /data --console-address ':9001'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: testawskey # use this as AWS S3 access key ID
      MINIO_ROOT_PASSWORD: testawssecret # use this as AWS S3 secret access key
      MINIO_SITE_REGION: eu-south-1
    volumes:
      - ./minio-data:/data
    restart: always

  elasticmq: # ElasticMQ is a local SQS-compatible queue system, to replace AWS SQS in local development
    image: softwaremill/elasticmq-native:1.5.7
    container_name: kpi-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq/elasticmq.local.conf:/opt/elasticmq.conf
    restart: always

networks:
  develop-network:
    name: interop-kpi-develop-network
    driver: bridge