version: "3"
name: pagopa-interop-kpi
services:

  postgres:
    container_name: postgres
    volumes:
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    image: postgres:15@sha256:9b1d34adbce1dd07ee6e94b4a2cf698884b89bd44a6c9c12f5da8f3acbfe4957
    ports:
      - 55000:5432
    environment:
      POSTGRES_DB: interop-kpi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -c 'max_connections=512' -c 'wal_level=logical'
  
  # MinIO is a local S3-compatible storage, to replace AWS S3 in local development
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-02-06T21-36-22Z@sha256:1f5e263a492659da3b5c165eeabe70fac1c186081d3fca6863fdc48c3e04856c
    entrypoint: >
      /usr/bin/minio server /data --console-address ':9001'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: testawskey # use this as AWS S3 access key ID
      MINIO_ROOT_PASSWORD: testawssecret # use this as AWS S3 secret access key
      MINIO_SITE_REGION: eu-south-1
    volumes:
      - ./minio-data:/data
    restart: always

  elasticmq: # ElasticMQ is a local SQS-compatible queue system, to replace AWS SQS in local development
    container_name: elasticmq 
    image: softwaremill/elasticmq-native:1.5.7@sha256:0cb5bcc04638c80af1631e8cf5da9b96b9fb6f46a4164462231065dc516c102f
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq/elasticmq.local.conf:/opt/elasticmq.conf
    restart: always

  zookeeper:
    image: quay.io/debezium/zookeeper:2.3@sha256:5b1354c4fa3bae600128eaa3ba9487ebd98b0aef40e3a39b32efe7533c8d2604

  kafka:
    image: quay.io/debezium/kafka:2.3@sha256:4009c39c2cc42686d1b5f0d2c46b3ff166e6ea98fb9a61d925b90f7fc56358e0
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:53a6553765a806eda9905c43bfcfe09da6812035@sha256:7317d08c1d58f1c7e67adb936e3b181151bd5534a30b761f75fe8bddbf079ffd
    ports:
      - 8084:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092


networks:
  develop-network:
    name: interop-kpi-develop-network
    driver: bridge